//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeDiamondCemesterProjekt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public int KundeID { get; set; }
        public string Navn { get; set; }
        public string Email { get; set; }
        public int Saldo { get; set; }
    }
}
